
service: chronic-pain-tracker

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"

functions:
  create:
    handler: pain/create.create
    events:
      - http:
          path: pain-entries
          method: post
          cors: true
  list:
    handler: pain/list.list
    events:
      - http:
         path: pain-entries
         method: get
         cors: true
  get:
    handler: pain/get.get
    events:
      - http:
        path: pain-entries/{entryid}
        method: get
        cors: true

resources:
  Resources:
    PainDynamodbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: userid
            AttributeType: S
          - AttributeName: entryid
            AttributeType: S
        KeySchema:
          - AttributeName: userid
            KeyType: HASH
          - AttributeName: entryid
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.TABLE_NAME}
